### ISSUE TITLE
Can't run jest tests with knapsack (config error)

### ISSUE THREAD

**Issue by samsternatretool** [KnapsackPro/knapsack-pro-js#98]
- [ ] I tagged with the correct `@knapsack-pro/PACKAGE` label

I am trying to use knapsack-pro-jest and all of my tests are failing with an error like this:
```
/retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/normalize.js:362
--
  | options[key].map(pattern =>
  | ^
  |  
  | TypeError: options[key].map is not a function
  | at normalizeUnmockedModulePathPatterns (/retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/normalize.js:362:16)
  | at /retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/normalize.js:755:17
  | at Array.reduce (<anonymous>)
  | at normalize (/retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/normalize.js:608:14)
  | at readConfig (/retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/index.js:160:74)
  | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | at async readConfigs (/retool/node_modules/.pnpm/jest-config@29.7.0_@types+node@18.18.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@_3hz3bb76buvcwcdh47thjjqrsq/node_modules/jest-config/build/index.js:424:26)
  | at async Object.runCLI (/retool/node_modules/.pnpm/@jest+core@29.7.0_node-notifier@8.0.2_ts-node@10.9.2_@swc+core@1.3.107_@swc+helpers@0.5.3__@t_iumvvgmpyrdky7inoqgggqyk2y/node_modules/@jest/core/build/cli/index.js:151:59)
  | at async onSuccess (/retool/node_modules/.pnpm/@knapsack-pro+jest@8.1.0_debug@2.6.9_jest@29.7.0_@types+node@18.18.2_node-notifier@8.0.2_ts-n_ybdjl4dm2h7ckguxj2ttqczjhe/node_modules/@knapsack-pro/jest/lib/knapsack-pro-jest.js:23:70)
```

I am passing the following arguments to the CLI, which are exactly what I passed to `jest` before:
```
--workerIdleMemoryLimit=500M --config=jest.config.cjs "--testTimeout=60000" "--filter" "<rootDir>/src/jesty/failedTestFilter.cjs" "--testSequencer=./src/jesty/shardSequencer.cjs" "--testPathIgnorePatterns=src/components/plugins/widgets/v2/frameworkTests/.*" "--reporters=default" "--reporters=jest-junit" "--silent" "--maxWorkers=3"
```

Seems like it does not like my config, but I am not getting any help from that error message. Any ideas? This is a **very** large codebase with thousands of tests (`.js`, `.ts`, `.jsx`, and `.tsx`) so providing an isolated repro will be difficult.

**Comment by samsternatretool** [comment]
Ah this is caused by the `--testPathIgnorePatterns`

**Comment by samsternatretool** [comment]
Closing this because I have a workaround, but just for some feedback here: it was very surprising to me that unlike running `jest $args`, running `knapsack-pro-jest $args` does **not** automatically pick up `jest.config.js`. That took me a long time to figure out.

**Comment by ArturT** [comment]
I'm happy that you solved the issue.

Thanks for the feedback.

We have documented how to pass Jest config:
https://docs.knapsackpro.com/jest/cookbook/#use-a-jest-config-file
but it's not part of the installation guide step.
https://docs.knapsackpro.com/jest/guide/?ci=github-actions&cra=no
I'll think about how to improve that.
